# Generated by Django 2.1.7 on 2019-05-13 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0003_auto_20190511_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile_info',
            name='edu_awards',
            field=models.CharField(default='name', max_length=40),
        ),
        migrations.AddField(
            model_name='user_profile_info',
            name='edu_services',
            field=models.CharField(default='name', max_length=40),
        ),
        migrations.AddField(
            model_name='user_profile_info',
            name='principal_message',
            field=models.CharField(default='name', max_length=40),
        ),
        migrations.AlterField(
            model_name='user_profile_info',
            name='fac1_prlf',
            field=models.ImageField(upload_to='profile_pics'),
        ),
    ]
