# Generated by Django 2.1.7 on 2019-05-13 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0004_auto_20190513_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile_info',
            name='fac1_prlf',
            field=models.ImageField(blank=True, upload_to='profile_pics'),
        ),
    ]
