# Generated by Django 2.1.7 on 2019-06-09 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0008_auto_20190608_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile_info',
            name='fac1_prlf',
            field=models.ImageField(blank=True, upload_to='media/profile_pics'),
        ),
        migrations.AlterField(
            model_name='user_profile_info',
            name='fac2_prlf',
            field=models.ImageField(blank=True, upload_to='media/profile_pics'),
        ),
        migrations.AlterField(
            model_name='user_profile_info',
            name='fac3_prlf',
            field=models.ImageField(blank=True, upload_to='media/profile_pics'),
        ),
        migrations.AlterField(
            model_name='user_profile_info',
            name='fac4_prlf',
            field=models.ImageField(blank=True, upload_to='media/profile_pics'),
        ),
        migrations.AlterField(
            model_name='user_profile_info',
            name='fac5_prlf',
            field=models.ImageField(blank=True, upload_to='media/profile_pics'),
        ),
        migrations.AlterField(
            model_name='user_profile_info',
            name='fac6_prlf',
            field=models.ImageField(blank=True, upload_to='media/profile_pics'),
        ),
        migrations.AlterField(
            model_name='user_profile_info',
            name='principal_image',
            field=models.ImageField(blank=True, upload_to='media/profile_pics'),
        ),
        migrations.AlterField(
            model_name='user_profile_info',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='media/profile_pics'),
        ),
        migrations.AlterField(
            model_name='user_profile_info',
            name='sch_featured_img1',
            field=models.ImageField(blank=True, upload_to='media/profile_pics'),
        ),
        migrations.AlterField(
            model_name='user_profile_info',
            name='sch_featured_img2',
            field=models.ImageField(blank=True, upload_to='media/profile_pics'),
        ),
        migrations.AlterField(
            model_name='user_profile_info',
            name='sch_featured_img3',
            field=models.ImageField(blank=True, upload_to='media/profile_pics'),
        ),
        migrations.AlterField(
            model_name='user_profile_info',
            name='school_logo',
            field=models.ImageField(blank=True, upload_to='media/profile_pics'),
        ),
    ]
