# Generated by Django 2.1.7 on 2019-06-09 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0009_auto_20190609_1802'),
    ]

    operations = [
        migrations.CreateModel(
            name='test_model_form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('fac1_prlf', models.ImageField(upload_to='media')),
            ],
        ),
    ]
