# Generated by Django 2.1.7 on 2019-06-09 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0010_test_model_form'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test_model_form',
            name='fac1_prlf',
        ),
    ]
