# Generated by Django 2.1.7 on 2019-06-09 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0011_remove_test_model_form_fac1_prlf'),
    ]

    operations = [
        migrations.AddField(
            model_name='test_model_form',
            name='fac1_prlf',
            field=models.ImageField(blank=True, upload_to='media'),
        ),
    ]
