# Generated by Django 2.1.7 on 2019-06-09 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0012_test_model_form_fac1_prlf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test_model_form',
            name='fac1_prlf',
        ),
        migrations.AddField(
            model_name='test_model_form',
            name='pic',
            field=models.FileField(blank=True, upload_to='profile_pics/'),
        ),
    ]
