# Generated by Django 2.1.7 on 2019-06-10 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0014_auto_20190609_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile_info',
            name='principal_message',
            field=models.CharField(default='name', max_length=400),
        ),
    ]
